CREATE DATABASE IF NOT EXISTS portfolioweb
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE portfolioweb;

CREATE TABLE IF NOT EXISTS messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  is_read TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
